print("Bienvenido")
print("Por favor ingrese su peso en kilogramos")
peso=input()
print ("Su peso es "+peso)
print("Por favor ingrese su estatura en metros")
altura=input()
print("Su estatura es "+altura)
IndiceDeMasaCorporal = round((float(peso)/(float(altura)*float(altura))),2)
print("Su indice de masa corporal es "+str(IndiceDeMasaCorporal))